# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  solution: '**/*.sln'
  projects: '**/*.csproj'
  adminUiProject: 'PM.UserAdmin.UI/PM.UserAdmin.UI.csproj'
  vendorUiProject: 'PM.Vendor.UI/PM.Vendor.UI.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

- task: UseDotNet@2
  displayName: "Install .NET Core 2.2.101"
  inputs:
    packageType: 'sdk'
    version: '2.2.101'

- task: DotNetCoreCLI@2
  displayName: "Restore Packages"
  inputs:
    command: 'restore'
    projects: '$(projects)'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: "Publish Admin UI - Dev"
  inputs:
    command: 'build'
    publishWebProjects: false
    arguments: '$(adminUiProject) /p:DeployOnBuild=true /p:PublishProfile=Development'

- task: CopyFiles@2
  displayName: "Copy Admin UI - Dev File To Artifact"
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
      obj\Debug\netcoreapp2.2\PubTmp\Out\**
    TargetFolder: '$(Build.ArtifactStagingDirectory)\Dev\Admin'

- task: DotNetCoreCLI@2
  displayName: "Publish Vendor UI - Dev"
  inputs:
    command: 'build'
    publishWebProjects: false
    arguments: '$(vendorUiProject) /p:DeployOnBuild=true /p:PublishProfile=Development'

- task: CopyFiles@2
  displayName: "Copy Vendor UI - Dev File To Artifact"
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: 'PM.Vendor.UI/Publish/Dev/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/Dev/Vendor'

- task: PublishBuildArtifacts@1
  displayName: "Publish Artifact"
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'