# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  solution: '**/*.sln'
  projects: '**/*.csproj'
  adminUiProject: 'PM.UserAdmin.UI/PM.UserAdmin.UI.csproj'
  vendorUiProject: 'PM.Vendor.UI/PM.Vendor.UI.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

- task: UseDotNet@2
  displayName: "Install .NET Core 2.2.101"
  inputs:
    packageType: 'sdk'
    version: '2.2.101'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(projects)'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    arguments: '$(adminUiProject) /p:Development'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'PM.UserAdmin.UI/Publish/Dev'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/Dev/Admin'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    arguments: '$(vendorUiProject) /p:Development'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'PM.Vendor.UI/Publish/Dev'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/Dev/Vendor'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'